/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as ArchiveIndexRouteImport } from './routes/archive.index'
import { Route as ArchiveEntitiesRouteImport } from './routes/archive.entities'
import { Route as ArchiveGroupsRouteImport } from './routes/archive.groups'
import { Route as ArchiveLevelsRouteImport } from './routes/archive.levels'
import { Route as ArchiveObjectsRouteImport } from './routes/archive.objects'
import { Route as ArchiveOriginsRouteImport } from './routes/archive.origins'
import { Route as ArchivePersonsRouteImport } from './routes/archive.persons'
import { Route as ArchivePhenomenaRouteImport } from './routes/archive.phenomena'
import { Route as ArchiveSurvivalRouteImport } from './routes/archive.survival'
import { Route as ArchiveEntitiesIndexRouteImport } from './routes/archive.entities.index'
import { Route as ArchiveEntitiesIdRouteImport } from './routes/archive.entities.$id'
import { Route as ArchiveGroupsIndexRouteImport } from './routes/archive.groups.index'
import { Route as ArchiveGroupsIdRouteImport } from './routes/archive.groups.$id'
import { Route as ArchiveLevelsIndexRouteImport } from './routes/archive.levels.index'
import { Route as ArchiveLevelsIdRouteImport } from './routes/archive.levels.$id'
import { Route as ArchiveObjectsIndexRouteImport } from './routes/archive.objects.index'
import { Route as ArchiveObjectsIdRouteImport } from './routes/archive.objects.$id'
import { Route as ArchivePersonsIndexRouteImport } from './routes/archive.persons.index'
import { Route as ArchivePersonsIdRouteImport } from './routes/archive.persons.$id'
import { Route as ArchivePhenomenaIndexRouteImport } from './routes/archive.phenomena.index'
import { Route as ArchivePhenomenaIdRouteImport } from './routes/archive.phenomena.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveIndexRoute = ArchiveIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ArchiveRoute,
} as any)
const ArchiveEntitiesRoute = ArchiveEntitiesRouteImport.update({
  id: '/entities',
  path: '/entities',
  getParentRoute: () => ArchiveRoute,
} as any)
const ArchiveGroupsRoute = ArchiveGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => ArchiveRoute,
} as any)
const ArchiveLevelsRoute = ArchiveLevelsRouteImport.update({
  id: '/levels',
  path: '/levels',
  getParentRoute: () => ArchiveRoute,
} as any)
const ArchiveObjectsRoute = ArchiveObjectsRouteImport.update({
  id: '/objects',
  path: '/objects',
  getParentRoute: () => ArchiveRoute,
} as any)
const ArchiveOriginsRoute = ArchiveOriginsRouteImport.update({
  id: '/origins',
  path: '/origins',
  getParentRoute: () => ArchiveRoute,
} as any)
const ArchivePersonsRoute = ArchivePersonsRouteImport.update({
  id: '/persons',
  path: '/persons',
  getParentRoute: () => ArchiveRoute,
} as any)
const ArchivePhenomenaRoute = ArchivePhenomenaRouteImport.update({
  id: '/phenomena',
  path: '/phenomena',
  getParentRoute: () => ArchiveRoute,
} as any)
const ArchiveSurvivalRoute = ArchiveSurvivalRouteImport.update({
  id: '/survival',
  path: '/survival',
  getParentRoute: () => ArchiveRoute,
} as any)
const ArchiveEntitiesIndexRoute = ArchiveEntitiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ArchiveEntitiesRoute,
} as any)
const ArchiveEntitiesIdRoute = ArchiveEntitiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ArchiveEntitiesRoute,
} as any)
const ArchiveGroupsIndexRoute = ArchiveGroupsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ArchiveGroupsRoute,
} as any)
const ArchiveGroupsIdRoute = ArchiveGroupsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ArchiveGroupsRoute,
} as any)
const ArchiveLevelsIndexRoute = ArchiveLevelsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ArchiveLevelsRoute,
} as any)
const ArchiveLevelsIdRoute = ArchiveLevelsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ArchiveLevelsRoute,
} as any)
const ArchiveObjectsIndexRoute = ArchiveObjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ArchiveObjectsRoute,
} as any)
const ArchiveObjectsIdRoute = ArchiveObjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ArchiveObjectsRoute,
} as any)
const ArchivePersonsIndexRoute = ArchivePersonsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ArchivePersonsRoute,
} as any)
const ArchivePersonsIdRoute = ArchivePersonsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ArchivePersonsRoute,
} as any)
const ArchivePhenomenaIndexRoute = ArchivePhenomenaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ArchivePhenomenaRoute,
} as any)
const ArchivePhenomenaIdRoute = ArchivePhenomenaIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ArchivePhenomenaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRouteWithChildren
  '/archive/entities': typeof ArchiveEntitiesRouteWithChildren
  '/archive/groups': typeof ArchiveGroupsRouteWithChildren
  '/archive/levels': typeof ArchiveLevelsRouteWithChildren
  '/archive/objects': typeof ArchiveObjectsRouteWithChildren
  '/archive/origins': typeof ArchiveOriginsRoute
  '/archive/persons': typeof ArchivePersonsRouteWithChildren
  '/archive/phenomena': typeof ArchivePhenomenaRouteWithChildren
  '/archive/survival': typeof ArchiveSurvivalRoute
  '/archive/': typeof ArchiveIndexRoute
  '/archive/entities/$id': typeof ArchiveEntitiesIdRoute
  '/archive/groups/$id': typeof ArchiveGroupsIdRoute
  '/archive/levels/$id': typeof ArchiveLevelsIdRoute
  '/archive/objects/$id': typeof ArchiveObjectsIdRoute
  '/archive/persons/$id': typeof ArchivePersonsIdRoute
  '/archive/phenomena/$id': typeof ArchivePhenomenaIdRoute
  '/archive/entities/': typeof ArchiveEntitiesIndexRoute
  '/archive/groups/': typeof ArchiveGroupsIndexRoute
  '/archive/levels/': typeof ArchiveLevelsIndexRoute
  '/archive/objects/': typeof ArchiveObjectsIndexRoute
  '/archive/persons/': typeof ArchivePersonsIndexRoute
  '/archive/phenomena/': typeof ArchivePhenomenaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/archive/origins': typeof ArchiveOriginsRoute
  '/archive/survival': typeof ArchiveSurvivalRoute
  '/archive': typeof ArchiveIndexRoute
  '/archive/entities/$id': typeof ArchiveEntitiesIdRoute
  '/archive/groups/$id': typeof ArchiveGroupsIdRoute
  '/archive/levels/$id': typeof ArchiveLevelsIdRoute
  '/archive/objects/$id': typeof ArchiveObjectsIdRoute
  '/archive/persons/$id': typeof ArchivePersonsIdRoute
  '/archive/phenomena/$id': typeof ArchivePhenomenaIdRoute
  '/archive/entities': typeof ArchiveEntitiesIndexRoute
  '/archive/groups': typeof ArchiveGroupsIndexRoute
  '/archive/levels': typeof ArchiveLevelsIndexRoute
  '/archive/objects': typeof ArchiveObjectsIndexRoute
  '/archive/persons': typeof ArchivePersonsIndexRoute
  '/archive/phenomena': typeof ArchivePhenomenaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRouteWithChildren
  '/archive/entities': typeof ArchiveEntitiesRouteWithChildren
  '/archive/groups': typeof ArchiveGroupsRouteWithChildren
  '/archive/levels': typeof ArchiveLevelsRouteWithChildren
  '/archive/objects': typeof ArchiveObjectsRouteWithChildren
  '/archive/origins': typeof ArchiveOriginsRoute
  '/archive/persons': typeof ArchivePersonsRouteWithChildren
  '/archive/phenomena': typeof ArchivePhenomenaRouteWithChildren
  '/archive/survival': typeof ArchiveSurvivalRoute
  '/archive/': typeof ArchiveIndexRoute
  '/archive/entities/$id': typeof ArchiveEntitiesIdRoute
  '/archive/groups/$id': typeof ArchiveGroupsIdRoute
  '/archive/levels/$id': typeof ArchiveLevelsIdRoute
  '/archive/objects/$id': typeof ArchiveObjectsIdRoute
  '/archive/persons/$id': typeof ArchivePersonsIdRoute
  '/archive/phenomena/$id': typeof ArchivePhenomenaIdRoute
  '/archive/entities/': typeof ArchiveEntitiesIndexRoute
  '/archive/groups/': typeof ArchiveGroupsIndexRoute
  '/archive/levels/': typeof ArchiveLevelsIndexRoute
  '/archive/objects/': typeof ArchiveObjectsIndexRoute
  '/archive/persons/': typeof ArchivePersonsIndexRoute
  '/archive/phenomena/': typeof ArchivePhenomenaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/archive'
    | '/archive/entities'
    | '/archive/groups'
    | '/archive/levels'
    | '/archive/objects'
    | '/archive/origins'
    | '/archive/persons'
    | '/archive/phenomena'
    | '/archive/survival'
    | '/archive/'
    | '/archive/entities/$id'
    | '/archive/groups/$id'
    | '/archive/levels/$id'
    | '/archive/objects/$id'
    | '/archive/persons/$id'
    | '/archive/phenomena/$id'
    | '/archive/entities/'
    | '/archive/groups/'
    | '/archive/levels/'
    | '/archive/objects/'
    | '/archive/persons/'
    | '/archive/phenomena/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/archive/origins'
    | '/archive/survival'
    | '/archive'
    | '/archive/entities/$id'
    | '/archive/groups/$id'
    | '/archive/levels/$id'
    | '/archive/objects/$id'
    | '/archive/persons/$id'
    | '/archive/phenomena/$id'
    | '/archive/entities'
    | '/archive/groups'
    | '/archive/levels'
    | '/archive/objects'
    | '/archive/persons'
    | '/archive/phenomena'
  id:
    | '__root__'
    | '/'
    | '/archive'
    | '/archive/entities'
    | '/archive/groups'
    | '/archive/levels'
    | '/archive/objects'
    | '/archive/origins'
    | '/archive/persons'
    | '/archive/phenomena'
    | '/archive/survival'
    | '/archive/'
    | '/archive/entities/$id'
    | '/archive/groups/$id'
    | '/archive/levels/$id'
    | '/archive/objects/$id'
    | '/archive/persons/$id'
    | '/archive/phenomena/$id'
    | '/archive/entities/'
    | '/archive/groups/'
    | '/archive/levels/'
    | '/archive/objects/'
    | '/archive/persons/'
    | '/archive/phenomena/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchiveRoute: typeof ArchiveRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive/': {
      id: '/archive/'
      path: '/'
      fullPath: '/archive/'
      preLoaderRoute: typeof ArchiveIndexRouteImport
      parentRoute: typeof ArchiveRoute
    }
    '/archive/entities': {
      id: '/archive/entities'
      path: '/entities'
      fullPath: '/archive/entities'
      preLoaderRoute: typeof ArchiveEntitiesRouteImport
      parentRoute: typeof ArchiveRoute
    }
    '/archive/groups': {
      id: '/archive/groups'
      path: '/groups'
      fullPath: '/archive/groups'
      preLoaderRoute: typeof ArchiveGroupsRouteImport
      parentRoute: typeof ArchiveRoute
    }
    '/archive/levels': {
      id: '/archive/levels'
      path: '/levels'
      fullPath: '/archive/levels'
      preLoaderRoute: typeof ArchiveLevelsRouteImport
      parentRoute: typeof ArchiveRoute
    }
    '/archive/objects': {
      id: '/archive/objects'
      path: '/objects'
      fullPath: '/archive/objects'
      preLoaderRoute: typeof ArchiveObjectsRouteImport
      parentRoute: typeof ArchiveRoute
    }
    '/archive/origins': {
      id: '/archive/origins'
      path: '/origins'
      fullPath: '/archive/origins'
      preLoaderRoute: typeof ArchiveOriginsRouteImport
      parentRoute: typeof ArchiveRoute
    }
    '/archive/persons': {
      id: '/archive/persons'
      path: '/persons'
      fullPath: '/archive/persons'
      preLoaderRoute: typeof ArchivePersonsRouteImport
      parentRoute: typeof ArchiveRoute
    }
    '/archive/phenomena': {
      id: '/archive/phenomena'
      path: '/phenomena'
      fullPath: '/archive/phenomena'
      preLoaderRoute: typeof ArchivePhenomenaRouteImport
      parentRoute: typeof ArchiveRoute
    }
    '/archive/survival': {
      id: '/archive/survival'
      path: '/survival'
      fullPath: '/archive/survival'
      preLoaderRoute: typeof ArchiveSurvivalRouteImport
      parentRoute: typeof ArchiveRoute
    }
    '/archive/entities/': {
      id: '/archive/entities/'
      path: '/'
      fullPath: '/archive/entities/'
      preLoaderRoute: typeof ArchiveEntitiesIndexRouteImport
      parentRoute: typeof ArchiveEntitiesRoute
    }
    '/archive/entities/$id': {
      id: '/archive/entities/$id'
      path: '/$id'
      fullPath: '/archive/entities/$id'
      preLoaderRoute: typeof ArchiveEntitiesIdRouteImport
      parentRoute: typeof ArchiveEntitiesRoute
    }
    '/archive/groups/': {
      id: '/archive/groups/'
      path: '/'
      fullPath: '/archive/groups/'
      preLoaderRoute: typeof ArchiveGroupsIndexRouteImport
      parentRoute: typeof ArchiveGroupsRoute
    }
    '/archive/groups/$id': {
      id: '/archive/groups/$id'
      path: '/$id'
      fullPath: '/archive/groups/$id'
      preLoaderRoute: typeof ArchiveGroupsIdRouteImport
      parentRoute: typeof ArchiveGroupsRoute
    }
    '/archive/levels/': {
      id: '/archive/levels/'
      path: '/'
      fullPath: '/archive/levels/'
      preLoaderRoute: typeof ArchiveLevelsIndexRouteImport
      parentRoute: typeof ArchiveLevelsRoute
    }
    '/archive/levels/$id': {
      id: '/archive/levels/$id'
      path: '/$id'
      fullPath: '/archive/levels/$id'
      preLoaderRoute: typeof ArchiveLevelsIdRouteImport
      parentRoute: typeof ArchiveLevelsRoute
    }
    '/archive/objects/': {
      id: '/archive/objects/'
      path: '/'
      fullPath: '/archive/objects/'
      preLoaderRoute: typeof ArchiveObjectsIndexRouteImport
      parentRoute: typeof ArchiveObjectsRoute
    }
    '/archive/objects/$id': {
      id: '/archive/objects/$id'
      path: '/$id'
      fullPath: '/archive/objects/$id'
      preLoaderRoute: typeof ArchiveObjectsIdRouteImport
      parentRoute: typeof ArchiveObjectsRoute
    }
    '/archive/persons/': {
      id: '/archive/persons/'
      path: '/'
      fullPath: '/archive/persons/'
      preLoaderRoute: typeof ArchivePersonsIndexRouteImport
      parentRoute: typeof ArchivePersonsRoute
    }
    '/archive/persons/$id': {
      id: '/archive/persons/$id'
      path: '/$id'
      fullPath: '/archive/persons/$id'
      preLoaderRoute: typeof ArchivePersonsIdRouteImport
      parentRoute: typeof ArchivePersonsRoute
    }
    '/archive/phenomena/': {
      id: '/archive/phenomena/'
      path: '/'
      fullPath: '/archive/phenomena/'
      preLoaderRoute: typeof ArchivePhenomenaIndexRouteImport
      parentRoute: typeof ArchivePhenomenaRoute
    }
    '/archive/phenomena/$id': {
      id: '/archive/phenomena/$id'
      path: '/$id'
      fullPath: '/archive/phenomena/$id'
      preLoaderRoute: typeof ArchivePhenomenaIdRouteImport
      parentRoute: typeof ArchivePhenomenaRoute
    }
  }
}

interface ArchiveEntitiesRouteChildren {
  ArchiveEntitiesIdRoute: typeof ArchiveEntitiesIdRoute
  ArchiveEntitiesIndexRoute: typeof ArchiveEntitiesIndexRoute
}

const ArchiveEntitiesRouteChildren: ArchiveEntitiesRouteChildren = {
  ArchiveEntitiesIdRoute: ArchiveEntitiesIdRoute,
  ArchiveEntitiesIndexRoute: ArchiveEntitiesIndexRoute,
}

const ArchiveEntitiesRouteWithChildren = ArchiveEntitiesRoute._addFileChildren(
  ArchiveEntitiesRouteChildren,
)

interface ArchiveGroupsRouteChildren {
  ArchiveGroupsIdRoute: typeof ArchiveGroupsIdRoute
  ArchiveGroupsIndexRoute: typeof ArchiveGroupsIndexRoute
}

const ArchiveGroupsRouteChildren: ArchiveGroupsRouteChildren = {
  ArchiveGroupsIdRoute: ArchiveGroupsIdRoute,
  ArchiveGroupsIndexRoute: ArchiveGroupsIndexRoute,
}

const ArchiveGroupsRouteWithChildren = ArchiveGroupsRoute._addFileChildren(
  ArchiveGroupsRouteChildren,
)

interface ArchiveLevelsRouteChildren {
  ArchiveLevelsIdRoute: typeof ArchiveLevelsIdRoute
  ArchiveLevelsIndexRoute: typeof ArchiveLevelsIndexRoute
}

const ArchiveLevelsRouteChildren: ArchiveLevelsRouteChildren = {
  ArchiveLevelsIdRoute: ArchiveLevelsIdRoute,
  ArchiveLevelsIndexRoute: ArchiveLevelsIndexRoute,
}

const ArchiveLevelsRouteWithChildren = ArchiveLevelsRoute._addFileChildren(
  ArchiveLevelsRouteChildren,
)

interface ArchiveObjectsRouteChildren {
  ArchiveObjectsIdRoute: typeof ArchiveObjectsIdRoute
  ArchiveObjectsIndexRoute: typeof ArchiveObjectsIndexRoute
}

const ArchiveObjectsRouteChildren: ArchiveObjectsRouteChildren = {
  ArchiveObjectsIdRoute: ArchiveObjectsIdRoute,
  ArchiveObjectsIndexRoute: ArchiveObjectsIndexRoute,
}

const ArchiveObjectsRouteWithChildren = ArchiveObjectsRoute._addFileChildren(
  ArchiveObjectsRouteChildren,
)

interface ArchivePersonsRouteChildren {
  ArchivePersonsIdRoute: typeof ArchivePersonsIdRoute
  ArchivePersonsIndexRoute: typeof ArchivePersonsIndexRoute
}

const ArchivePersonsRouteChildren: ArchivePersonsRouteChildren = {
  ArchivePersonsIdRoute: ArchivePersonsIdRoute,
  ArchivePersonsIndexRoute: ArchivePersonsIndexRoute,
}

const ArchivePersonsRouteWithChildren = ArchivePersonsRoute._addFileChildren(
  ArchivePersonsRouteChildren,
)

interface ArchivePhenomenaRouteChildren {
  ArchivePhenomenaIdRoute: typeof ArchivePhenomenaIdRoute
  ArchivePhenomenaIndexRoute: typeof ArchivePhenomenaIndexRoute
}

const ArchivePhenomenaRouteChildren: ArchivePhenomenaRouteChildren = {
  ArchivePhenomenaIdRoute: ArchivePhenomenaIdRoute,
  ArchivePhenomenaIndexRoute: ArchivePhenomenaIndexRoute,
}

const ArchivePhenomenaRouteWithChildren =
  ArchivePhenomenaRoute._addFileChildren(ArchivePhenomenaRouteChildren)

interface ArchiveRouteChildren {
  ArchiveEntitiesRoute: typeof ArchiveEntitiesRouteWithChildren
  ArchiveGroupsRoute: typeof ArchiveGroupsRouteWithChildren
  ArchiveLevelsRoute: typeof ArchiveLevelsRouteWithChildren
  ArchiveObjectsRoute: typeof ArchiveObjectsRouteWithChildren
  ArchiveOriginsRoute: typeof ArchiveOriginsRoute
  ArchivePersonsRoute: typeof ArchivePersonsRouteWithChildren
  ArchivePhenomenaRoute: typeof ArchivePhenomenaRouteWithChildren
  ArchiveSurvivalRoute: typeof ArchiveSurvivalRoute
  ArchiveIndexRoute: typeof ArchiveIndexRoute
}

const ArchiveRouteChildren: ArchiveRouteChildren = {
  ArchiveEntitiesRoute: ArchiveEntitiesRouteWithChildren,
  ArchiveGroupsRoute: ArchiveGroupsRouteWithChildren,
  ArchiveLevelsRoute: ArchiveLevelsRouteWithChildren,
  ArchiveObjectsRoute: ArchiveObjectsRouteWithChildren,
  ArchiveOriginsRoute: ArchiveOriginsRoute,
  ArchivePersonsRoute: ArchivePersonsRouteWithChildren,
  ArchivePhenomenaRoute: ArchivePhenomenaRouteWithChildren,
  ArchiveSurvivalRoute: ArchiveSurvivalRoute,
  ArchiveIndexRoute: ArchiveIndexRoute,
}

const ArchiveRouteWithChildren =
  ArchiveRoute._addFileChildren(ArchiveRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchiveRoute: ArchiveRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
